In [3]:
pip install numpy

In [2]:
# Importando no ambiente de desenvolvimento
import numpy as np

# Criação de Arrays

In [6]:
# Visualizar diversos exemplos de como utilizar 
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [7]:
# Array 1D: [1, 2, 3]
l = [1, 2, 3]
x = np.array(l)
print("X: ", x)
print("Shape: ", x.shape) # Fala a quantidade de elementos em cada dimensão

X:  [1 2 3]
Shape:  (3,)


In [8]:
type(x)

numpy.ndarray

In [10]:
# Criação de um array 2D: listas aninhadas
l = [[1, 2], [3, 4]] # Cada posição representa uma linha dentro do array
x = np.array(l)
print("X: \n", x)
print("Shape:", x.shape)

X: 
 [[1 2]
 [3 4]]
Shape: (2, 2)


In [12]:
# Array contendo apenas 0's
dim = (2, 2) # (linhas, colunas)
x = np.zeros(dim) # Recebe uma tupla
print("X: \n", x)
print("Shape:", x.shape)

X: 
 [[0. 0.]
 [0. 0.]]
Shape: (2, 2)


In [13]:
# Array contendo apenas 1's
size = (2, 2) # (linhas, colunas)
x = np.ones(size) # Recebe uma tupla
print("X: \n", x)
print("Shape:", x.shape)

X: 
 [[1. 1.]
 [1. 1.]]
Shape: (2, 2)


In [15]:
# np.linspace?
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [16]:
# Criação de valores dentro de um intervalo
# valores uniformes entre 5 e 15
x_min, x_max = 5, 15
x = np.linspace(start = x_min, stop = x_max, num = 6) # vou gerar 6 pontos linearmente espaçados
print("X: \n", x)
print("Shape:", x.shape)

X: 
 [ 5.  7.  9. 11. 13. 15.]
Shape: (6,)


In [17]:
# Criação da matriz identidade
n = 4
x = np.eye(n) # Eye representa a matriz identidade, onde a diagonal principal é composta por 1's e os outros elementos 0's
# Eye recebe um inteiro
print("X: \n", x)
print("Shape:", x.shape)

X: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Shape: (4, 4)


In [18]:
# Criação de valores aleatórios
# np.random.seed(10)
x = np.random.random(size=(2, 3)) # retorna valores aleatórios entre 0 e 1 uniformemente, um array 2x3
print("X: \n", x)
print("Shape:", x.shape)

X: 
 [[0.80024631 0.69278467 0.47081986]
 [0.75824937 0.70052211 0.77463808]]
Shape: (2, 3)


In [3]:
x = np.array ([[1, 3, 7], [4, 11, 21],[42, 8, 9]])
print("x:\n", x)

x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]
