In [9]:
import numpy as np

# Comparações

## Comparações Booleanas

In [2]:
A = np.array([1, 2, 3])
B = np.array([2, 0, 2])
s = 3

## Menor

In [4]:
print("Comparação menor:")
print(A < B)
print(A < s)

Comparação menor:
[ True False False]
[ True  True False]


## Menor ou igual

In [6]:
print("Comparação menor ou igual:")
print(A <= B)
print(A <= s)

Comparação menor ou igual:
[ True False False]
[ True  True  True]


## Maior

In [8]:
print("Comparação maior:")
print(A > B)
print(A > s)

Comparação maior:
[False  True  True]
[False False False]


# Maior ou igual

In [10]:
print("Comparação menor ou igual:")
print(A >= B)
print(A >= s)

Comparação menor ou igual:
[False  True  True]
[False False  True]


## Igual

In [13]:
print("Comparação de igualdade:")
print(A == B)
print(A == s)

Comparação de igualdade:
[False False False]
[False False  True]


# Indexação Booleana

## Operação de Filtro

In [3]:
# indexação booleana: um novo subarray contendo uma 
# cópia dos elementos em que a condição de verificação se aplica
cond = A <= 2
D = A[cond] # Cria um array com os números que passam na condição acima
print("A:", A)
print("Condição:", cond)
print("D:", D)

A: [1 2 3]
Condição: [ True  True False]
D: [1 2]


## Comparação

In [10]:
# Criação dos arrays
x = np.array([[1, 2], [3, 4]])
y = np.array([1.5, 3.5])
print("X: \n", x)
print("Y: \n", y)

X: 
 [[1 2]
 [3 4]]
Y: 
 [1.5 3.5]


### Comparações ponto a ponto

In [11]:
# Comparações ponto a ponto
print("Comparação de um array com um escalar (>): \n", x > 2)
print("Comparação de um array com um escalar (>=): \n", x >= 2)
print("Comparação de um array com um escalar (<): \n", x < 2)
print("Comparação de um array com um escalar (<=): \n", x <= 2)
print("Comparação entre arrays (==): \n", x == x)
print("Comparação entre arrays (>): \n", x > x)
print("Comparação entre arrays (>): \n", x > y) # broadcasting

Comparação de um array com um escalar (>): 
 [[False False]
 [ True  True]]
Comparação de um array com um escalar (>=): 
 [[False  True]
 [ True  True]]
Comparação de um array com um escalar (<): 
 [[ True False]
 [False False]]
Comparação de um array com um escalar (<=): 
 [[ True  True]
 [False False]]
Comparação entre arrays (==): 
 [[ True  True]
 [ True  True]]
Comparação entre arrays (>): 
 [[False False]
 [False False]]
Comparação entre arrays (>): 
 [[False False]
 [ True  True]]


## Indexação Booleana

In [16]:
x = np.array([[1, 3, 7], [4, 11, 21], [42, 8, 9]])
print("X: \n", x)

X: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


### Retornar um número de elementos maiores do que um determinado valor

In [26]:
# Maiores que k
k = 10
cond = x > k
print("Condição: \n", cond, "\n")
print(f'Elementos maiores que {k}:', x[cond], "\n")
print(f'Número de elementos maiores que {k}:', len(x[cond]))

Condição: 
 [[False False False]
 [False  True  True]
 [ True False False]] 

Elementos maiores que 10: [11 21 42] 

Número de elementos maiores que 10: 3


### Extração dos números pares

In [24]:
cond = x % 2 == 0 # números pares
print("X: \n", x, "\n")
print("Condição: \n", cond, "\n")
print("Números pares:", x[cond])

X: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]] 

Condição: 
 [[False False False]
 [ True False False]
 [ True  True False]] 

Números pares: [ 4 42  8]


### Extração dos números Ímpares

In [25]:
cond = x % 2 != 0 # números ímpares ou cond = x % 2 == 1
print("X: \n", x, "\n")
print("Condição: \n", cond, "\n")
print("Números pares:", x[cond])

X: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]] 

Condição: 
 [[ True  True  True]
 [False  True  True]
 [False False  True]] 

Números pares: [ 1  3  7 11 21  9]
