In [3]:
import numpy as np

In [4]:
# Os índices no Python vão de 0 a n-1
# onde n é tamanho da dimensão
x = np.linspace(start=10, stop=100, num=10)
print("X:", x)
print("Shape:", x.shape)

X: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
Shape: (10,)


In [8]:
# Extração de elementos
print("X:", x, "\n")
print("Primeiro Elemento:", x[0])
print("Segundo Elemento:", x[1])
print("Último Elemento:", x[9])
print("Último Elemento:", x[-1])
print("Penúltimo Elemento:", x[-2])

X: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.] 

Primeiro Elemento: 10.0
Segundo Elemento: 20.0
Último Elemento: 100.0
Último Elemento: 100.0
Penúltimo Elemento: 90.0


In [9]:
# Slicing: extração de subarrays
print("X:", x, "\n")
print("Dois primeiros elementos", x[0:2])
print("Dois primeiros elementos", x[:2])
print("Dois últimos elementos", x[-2:])

X: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.] 

Dois primeiros elementos [10. 20.]
Dois primeiros elementos [10. 20.]
Dois últimos elementos [ 90. 100.]


In [10]:
# Slicing em arrays 2D (Matrizes)
x = x.reshape(2, 5) #reshape de x para 2 linhas e 5 colunas
# remodela o array original
print("x:\n", x)

x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]


In [11]:
# Extração de elementos
print("Primeira linha, segunda coluna", x[0, 1])
print("Segunda linha, penúltima coluna", x[1, -2])
print("Última linha, última coluna", x[1, 4])
print("Última linha, última coluna", x[1, -1])

Primeira linha, segunda coluna 20.0
Segunda linha, penúltima coluna 90.0
Última linha, última coluna 100.0
Última linha, última coluna 100.0


In [13]:
# Slicing: extração de subarrays
print("x:\n", x, "\n")
print("Primeira linha inteira: ", x[0, :])
print("Primeira linha, segunda a quarta coluna: ", x[0, 1:4])
print("Última coluna inteira:\n", x[:, [-1]])

x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]] 

Primeira linha inteira:  [10. 20. 30. 40. 50.]
Primeira linha, segunda a quarta coluna:  [20. 30. 40.]
Última coluna inteira:
 [[ 50.]
 [100.]]


In [14]:
# Atenção com compartilhamento de memória em subarrays!!
x = np.array([1, 2, 3])
print("x antes:", x)
y = x[:2]
y[0] = -100 # alteração do valor em y altera o valor de x
print("x depois:", x)

x antes: [1 2 3]
x depois: [-100    2    3]


In [16]:
# Atenção com compartilhamento de memória em subarrays!!
x = np.array([1, 2, 3])
print("x antes:", x)
y = x[:2].copy() # evita que a alteração feita em y seja também feita em x
y[0] = -100 # alteração do valor em y altera o valor de x
print("x depois:", x)
print("y:", y)

x antes: [1 2 3]
x depois: [1 2 3]
y: [-100    2]
