In [1]:
import numpy as np

# Operações Aritméticas

In [2]:
# Criação de dois arrays x e y
x = np.ones((2, 2))
y = np.eye(2)
print("x: \n", x)
print("y: \n", y)

x: 
 [[1. 1.]
 [1. 1.]]
y: 
 [[1. 0.]
 [0. 1.]]


## Soma

In [3]:
print("Soma de dois arrays: \n", x + y)
print("Soma com float/int:\n", x + 2.) #broadcasting, o 2 será somado a todos os elementos do x - 2 int, 2. float 

Soma de dois arrays: 
 [[2. 1.]
 [1. 2.]]
Soma com float/int:
 [[3. 3.]
 [3. 3.]]


## Subtração

In [4]:
print("Subtração de dois arrays: \n", x - y)
print("Subtração com float/int:\n", x - 2.) #broadcasting

Subtração de dois arrays: 
 [[0. 1.]
 [1. 0.]]
Subtração com float/int:
 [[-1. -1.]
 [-1. -1.]]


## Divisão

In [5]:
print("Divisão de dois arrays: \n", x / y)
print("Divisão com float/int:\n", x / 2) #broadcasting

Divisão de dois arrays: 
 [[ 1. inf]
 [inf  1.]]
Divisão com float/int:
 [[0.5 0.5]
 [0.5 0.5]]


C:\Users\carme\AppData\Local\Temp\ipykernel_8380\1227312385.py:2: RuntimeWarning: divide by zero encountered in divide
  print("Divisão de dois arrays: \n", x / y)


In [7]:
# Quando o broadcasting não funciona
# np.array([1, 2, 3]) + np.array([1, 2])
# As dimensões são inconsistentes

## Combinação de operações

In [8]:
# Soma, subtração e divisão
print("Combinação de operações: \n", (x + y) / (x - y))

Combinação de operações: 
 [[inf  1.]
 [ 1. inf]]


C:\Users\carme\AppData\Local\Temp\ipykernel_8380\166789434.py:2: RuntimeWarning: divide by zero encountered in divide
  print("Combinação de operações: \n", (x + y) / (x - y))


# Operações Matriciais 

## Multiplicação

In [9]:
# Multiplicação elemento a elemento
print("x: \n", x)
print("y: \n", y)

x: 
 [[1. 1.]
 [1. 1.]]
y: 
 [[1. 0.]
 [0. 1.]]


In [10]:
# Multiplicação
print("Multiplicação de dois arrays: \n", x * y)
print("Multiplicação com float/int:\n", x * 2.) #broadcasting

Multiplicação de dois arrays: 
 [[1. 0.]
 [0. 1.]]
Multiplicação com float/int:
 [[2. 2.]
 [2. 2.]]


In [11]:
# Criando array simples contendo apenas o número 10
# Multiplicamos a matriz de 10x10 criada de apenas 1's por 10
10 * np.ones((10, 10))

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

## Multiplicação Matricial

In [13]:
print("Multiplicação Matricial (np.dot): \n", np.dot(x, y))
print("Multiplicação Matricial (@): \n", x @ y)
print("Multiplicação Matricial (.dot): \n", x.dot(y))

Multiplicação Matricial (np.dot): 
 [[1. 1.]
 [1. 1.]]
Multiplicação Matricial (@): 
 [[1. 1.]
 [1. 1.]]
Multiplicação Matricial (.dot): 
 [[1. 1.]
 [1. 1.]]


### Exemplo

In [ ]:
"""
Exemplo:
Solução de um sistema de equações:
    a + 2*b = 7
  3*a - 2*b = -11
  
Solução analítica: (a,b) = (-1, 4)
Matricialmente, este problema tem a seguinte forma:
    Ax = c, onde:
    - X = [a, b]
    - A = [[1,2], [3, -2]]
    - C = [7, -11]

Solução numérica: x = inv(A) @ C,
"""

In [19]:
# Definição do problema
A = np.array([[1, 2], [3, -2]])
C = np.array([[7], [-11]])
print("A: \n", A)
print("C: \n", C)

A: 
 [[ 1  2]
 [ 3 -2]]
C: 
 [[  7]
 [-11]]


In [20]:
# Solução
x = np.dot(np.linalg.inv(A), C)
# x = np.linalg.inv(A) @ C # inv faz a inversa da matriz
print("(a, b):", x.ravel())

(a, b): [-1.  4.]
