### Importando a Biblioteca Numpy

In [3]:
import numpy as np

# 1. Operações Úteis em Numpy

## Array

In [8]:
x = np.array([ [1, 3, 7], [4, 11, 21], [42, 8, 9]])
print("X: \n", x)

X: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


## 1.1 Reshape: Transformar a matriz em um vetor coluna

### 1.1.1 - (3, 3) virará (9, 1): 3x3 = 9x1 = 9

In [11]:
# Ele sai de um vetor com 3 linhas e 3 colunas para um vetor com 9 linhas e 1 coluna
print("Transformação de x em um vetor coluna: \n", x.reshape(9, 1))

Transformação de x em um vetor coluna: 
 [[ 1]
 [ 3]
 [ 7]
 [ 4]
 [11]
 [21]
 [42]
 [ 8]
 [ 9]]


## 1.2 Transposição de Matriz

Faz o que é linha virar coluna, e o que é coluna virar linha

In [15]:
print("X: \n", x, "\n")
print("X transposta: \n", x.T)

X: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]] 

X transposta: 
 [[ 1  4 42]
 [ 3 11  8]
 [ 7 21  9]]


## 1.3 Soma de elementos de uma Matriz

### np.sum:

Soma em um dado eixo, axis = {0: linha, 1: coluna}

In [17]:
print("X: \n", x, "\n")
print("Soma de todos os elementos de X:", np.sum(x))
print("Soma de X ao longo das linhas:", np.sum(x, axis=0))
print("Soma de X ao longo das colunas:", np.sum(x, axis=1))

X: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]] 

Soma de todos os elementos de X: 106
Soma de X ao longo das linhas: [47 22 37]
Soma de X ao longo das colunas: [11 36 59]


## 1.4 Média dos elementos

### np.mean:

Média de um dados eixo, axis = {0: linha, 1: coluna}

In [18]:
print("X: \n", x, "\n")
print("Média de todos os elementos de X:", np.mean(x))
print("Média de X ao longo das linhas:", np.mean(x, axis=0))
print("Média de X ao longo das colunas:", np.mean(x, axis=1))

X: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]] 

Média de todos os elementos de X: 11.777777777777779
Média de X ao longo das linhas: [15.66666667  7.33333333 12.33333333]
Média de X ao longo das colunas: [ 3.66666667 12.         19.66666667]


## 1.5 Identificando os Índices

### np.where:

Identificação dos índices onde uma dada condição é atendida.  
Uso conjunto com indexação booleana

In [20]:
print("X: \n", x, "\n")
cond = x % 2 == 0 # números pares
print("Condição: \n", cond, "\n")
i, j = np.where(cond) # índices x[i, j] = x[cond]
print("Índice i (linhas):", i)
print("Índice j (colunas):", j)

X: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]] 

Condição: 
 [[False False False]
 [ True False False]
 [ True  True False]] 

Índice i (linhas): [1 2 2]
Índice j (colunas): [0 0 1]


## 1.6 Indexação Booleana e Slicing

### Selecionar as linhas de x que possuem algum número par

In [22]:
print("X: \n", x, "\n")
cond = x % 2 == 0 # números pares
print("Condição: \n", cond)

X: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]] 

Condição: 
 [[False False False]
 [ True False False]
 [ True  True False]]


### # Se houver alguma condição True na linha, a soma será 0

In [24]:
i_row = np.where(np.sum(cond, axis=1))[0]
print("Índices das linhas que possuem números pares:", i_row, "\n")
print("Linhas que possuem números pares: \n", x[i_row, :])

Índices das linhas que possuem números pares: [1 2] 

Linhas que possuem números pares: 
 [[ 4 11 21]
 [42  8  9]]
